server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/carpool_auth
    username: root
    password: "Hardik@14"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwertyuiop"
  expiration: 86400000
