server:
  port: 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/carpool_employee
    username: root
    password: "Hardik@14"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwertyuiop"
